OUTPUT_PATH = "D:/AI/ComfyUI_windows_testing/ComfyUI/output"
INPUT_PATH = "D:/AI/ComfyUI_windows_testing/ComfyUI/input"
URL = "http://127.0.0.1:8188/prompt"
WORKFLOW_FILE = "workflows/sketch2image_api.json"
MISSING_SKETCH = "media/missing-sketch.jpg"