OUTPUT_PATH = r"C:\Users\Mehrad Bayat\Desktop\ComfyUI_windows_portable\ComfyUI\output"
INPUT_PATH = r"C:\Users\Mehrad Bayat\Desktop\ComfyUI_windows_portable\ComfyUI\input"
URL = "http://127.0.0.1:8188/prompt"
WORKFLOW_FILE = "workflows/sketch2image_api.json"
MISSING_SKETCH = "media/missing-sketch.jpg"